
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 236605
 */
public class BuildingsPanel extends javax.swing.JFrame {

    private Colony colonyData;
    /**
     * Creates new form BuildingsPanel
     */
    public BuildingsPanel() throws FileNotFoundException {
        initComponents();
        colonyData = new Colony();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildingNameLabel = new javax.swing.JLabel();
        buildingNameInput = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        buildingInformation = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        backtoMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1366, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buildingNameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buildingNameLabel.setText("Enter Building Name Below");
        getContentPane().add(buildingNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, 430, 90));

        buildingNameInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buildingNameInput.setText("Enter Building Name");
        getContentPane().add(buildingNameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 790, 80));

        enter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 300, 60));

        buildingInformation.setColumns(20);
        buildingInformation.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        buildingInformation.setRows(5);
        buildingInformation.setText("Command Center\nStorage Facility\nJunkyard\nResearch Building\nHydroponics\nGreenhouse\nMachinist Shop\nSmelter\nWater Treatment Facility\nHospital");
        jScrollPane1.setViewportView(buildingInformation);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 290, 400));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane2.setViewportView(output);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 960, 400));

        backtoMain.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backtoMain.setText("Back To Personnel");
        backtoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMainActionPerformed(evt);
            }
        });
        getContentPane().add(backtoMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 800, 690, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        try {
            String buildingName = buildingNameInput.getText();
            String result = colonyData.building(buildingName);
            output.setText(result);
        } catch (IOException ex) {
            Logger.getLogger(PromotionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enterActionPerformed

    private void backtoMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMainActionPerformed
        try {
            PersonnelPanel p = new PersonnelPanel();
            p.setVisible(true);
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PromotionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backtoMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildingsPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BuildingsPanel().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(BuildingsPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMain;
    private javax.swing.JTextArea buildingInformation;
    private javax.swing.JTextField buildingNameInput;
    private javax.swing.JLabel buildingNameLabel;
    private javax.swing.JButton enter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output;
    // End of variables declaration//GEN-END:variables
}
