/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 239023
 */
public class Generator implements Hub {
    
    private String name;
    private int powerGeneratedPerHour;
    
    
    /**
     * Summary: Creates an object of instance Generator using the PIV's
     * @param power: power generated by the generator
     */
    public Generator (int power)
    {
        name = "Power Generator";
        powerGeneratedPerHour = power;
    }
    
    
    /**
     * Summary: Returns the PIV String name
     * @return the name of the Generator
     */
    public String getName()
    {
        return name;
    }
    
    
    /**
     * Summary: Returns the PIV int power
     * @return the total amount of power contained in the Generator
     */
    public int getPower()
    {
        return powerGeneratedPerHour;
    }
    
    
    /**
     * Summary: Sets the PIV power to the given parameter newPowerAmount
     * @param amt
     */
    public void setPower(int newPowerAmount)
    {
        powerGeneratedPerHour = newPowerAmount;
    }
    
    
    /**
     * Summary: Creates a String representation of the building
     * 			using its name
     * @return the PIV name of the Generator
     */
    public String toString()
    {
    	return getName();
    }
    
    
    
    
}