
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 179923
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        missionToMarsTitle = new javax.swing.JLabel();
        clickButtonLabel = new javax.swing.JLabel();
        foodButton = new javax.swing.JButton();
        powerGridButton = new javax.swing.JButton();
        personnelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        missionToMarsTitle.setFont(new java.awt.Font("Wide Latin", 0, 24)); // NOI18N
        missionToMarsTitle.setForeground(new java.awt.Color(51, 153, 255));
        missionToMarsTitle.setText("Welcome to Plamanton!");
        getContentPane().add(missionToMarsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        clickButtonLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        clickButtonLabel.setText("Click on the button you would like to explore");
        getContentPane().add(clickButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        foodButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        foodButton.setText("Food");
        foodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodButtonActionPerformed(evt);
            }
        });
        getContentPane().add(foodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 198, 78));

        powerGridButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        powerGridButton.setText("Power Grid");
        powerGridButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powerGridButtonActionPerformed(evt);
            }
        });
        getContentPane().add(powerGridButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 198, 79));

        personnelButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        personnelButton.setText("Personnel");
        personnelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personnelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(personnelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 198, 79));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void foodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodButtonActionPerformed
        FoodFrame food = null;
        try {
            // TODO add your handling code here:
            food = new FoodFrame();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        food.setVisible(true);
    }//GEN-LAST:event_foodButtonActionPerformed

    private void powerGridButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powerGridButtonActionPerformed
        PowerGridFrame pg = null;
        try {
            // TODO add your handling code here:
            pg = new PowerGridFrame();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        pg.setVisible(true);
    }//GEN-LAST:event_powerGridButtonActionPerformed

    private void personnelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personnelButtonActionPerformed
        // TODO add your handling code here:
        PersonnelPanel personnel = null;
        try {
            personnel = new PersonnelPanel();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
        personnel.setVisible(true);
    }//GEN-LAST:event_personnelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clickButtonLabel;
    private javax.swing.JButton foodButton;
    private javax.swing.JLabel missionToMarsTitle;
    private javax.swing.JButton personnelButton;
    private javax.swing.JButton powerGridButton;
    // End of variables declaration//GEN-END:variables
}
