
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 236605
 */
public class PersonnelPanel extends javax.swing.JFrame {

    private Colony colonyData;
    /**
     * Creates new form PersonnelPanel
     */
    public PersonnelPanel() throws FileNotFoundException{
        initComponents();
        colonyData = new Colony();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promotion = new javax.swing.JButton();
        leadership = new javax.swing.JButton();
        buildings = new javax.swing.JButton();
        deceased = new javax.swing.JButton();
        jobLocationChange = new javax.swing.JButton();
        cleaningDuty = new javax.swing.JButton();
        sizer = new javax.swing.JButton();
        backToMain = new javax.swing.JButton();
        functionsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(getPreferredSize());
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(1366, 1024));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        promotion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        promotion.setText("Promotion");
        promotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                promotionActionPerformed(evt);
            }
        });
        getContentPane().add(promotion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 380, 80));

        leadership.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        leadership.setText("Leadership");
        leadership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leadershipActionPerformed(evt);
            }
        });
        getContentPane().add(leadership, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 130, 380, 80));

        buildings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        buildings.setText("Buildings");
        buildings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingsActionPerformed(evt);
            }
        });
        getContentPane().add(buildings, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 380, 80));

        deceased.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deceased.setText("Deceased");
        deceased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deceasedActionPerformed(evt);
            }
        });
        getContentPane().add(deceased, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 460, 380, 80));

        jobLocationChange.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jobLocationChange.setText("Job Location Change");
        jobLocationChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobLocationChangeActionPerformed(evt);
            }
        });
        getContentPane().add(jobLocationChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 380, 80));

        cleaningDuty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cleaningDuty.setText("Cleaning Duty");
        cleaningDuty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleaningDutyActionPerformed(evt);
            }
        });
        getContentPane().add(cleaningDuty, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 660, 380, 80));

        sizer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sizer.setText("Colony Size");
        sizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizerActionPerformed(evt);
            }
        });
        getContentPane().add(sizer, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 760, 380, 90));

        backToMain.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backToMain.setText("Back To Main");
        backToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMainActionPerformed(evt);
            }
        });
        getContentPane().add(backToMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 870, 380, 90));

        functionsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        functionsLabel.setText("Functions");
        functionsLabel.setAlignmentX(0.5F);
        getContentPane().add(functionsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 100, 60));

        display.setColumns(20);
        display.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 790, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leadershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leadershipActionPerformed
        try {
            String result = colonyData.leadership();
            display.setText(result);
            colonyData = new Colony();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_leadershipActionPerformed

    private void promotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_promotionActionPerformed
        try {
            PromotionPanel p = new PromotionPanel();
            p.setVisible(true);
            colonyData = new Colony();
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_promotionActionPerformed
    
    private void buildingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingsActionPerformed
        try {
            BuildingsPanel b = new BuildingsPanel();
            b.setVisible(true);
            colonyData = new Colony();
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buildingsActionPerformed
    
    private void deceasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deceasedActionPerformed
        try {
            DeceasedPanel d = new DeceasedPanel();
            d.setVisible(true);
            colonyData = new Colony();
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deceasedActionPerformed
    
    private void jobLocationChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobLocationChangeActionPerformed
        try {
            JobLocationChangePanel j = new JobLocationChangePanel();
            j.setVisible(true);
            colonyData = new Colony();
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jobLocationChangeActionPerformed

    private void sizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizerActionPerformed
        try {
            int result = colonyData.size();
            display.setText("Number of Colonists: " + result);
            colonyData = new Colony();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sizerActionPerformed

    private void cleaningDutyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleaningDutyActionPerformed
        // TODO add your handling code here:
        try {
            display.setText(colonyData.cleaningDuty());
            colonyData = new Colony();
            colonyData = new Colony();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cleaningDutyActionPerformed

    private void backToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMainActionPerformed
       MainFrame main = new MainFrame();
       dispose();
       main.setVisible(true);
    }//GEN-LAST:event_backToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(){
                try {
                    new PersonnelPanel().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PersonnelPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backToMain;
    private javax.swing.JButton buildings;
    private javax.swing.JButton cleaningDuty;
    private javax.swing.JButton deceased;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel functionsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jobLocationChange;
    private javax.swing.JButton leadership;
    private javax.swing.JButton promotion;
    private javax.swing.JButton sizer;
    // End of variables declaration//GEN-END:variables
}
