
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author anushkakhatri
 */
public class PowerGridFrame extends javax.swing.JFrame {

    private Grid powerGrid;
    
    /**
     * Creates new form PowerGridFrame
     */
    public PowerGridFrame() throws FileNotFoundException {
        initComponents();
        
        powerGrid  = new Grid("Buildings.dat", "Connections.dat", "PowerGridUpdater.dat");
        infoDisplay.setText(powerGrid.displayInformation());
        
        String powerGridStatus = "Power Grid Status: Running Successfully";
        gridStatus.setText(powerGridStatus);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        infoDisplay = new javax.swing.JTextArea();
        displayInfoButton = new javax.swing.JButton();
        displayShortestPathButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        gridLosses = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        gridStatus = new javax.swing.JTextArea();
        updateInformationButton = new javax.swing.JButton();
        updateFromFileButton = new javax.swing.JButton();
        systemUpdatesButton = new javax.swing.JLabel();
        adjustPowerLabel = new javax.swing.JLabel();
        buildingNameField = new javax.swing.JTextField();
        amountOfPowerField = new javax.swing.JTextField();
        adjustPowerButton = new javax.swing.JButton();
        mainPageButton = new javax.swing.JButton();
        displayConnectionsButton = new javax.swing.JButton();
        firstHubNameField = new javax.swing.JTextField();
        secondHubNameField = new javax.swing.JTextField();
        terminalNameField = new javax.swing.JTextField();
        addConnectionButton = new javax.swing.JButton();
        removeConnectionButton = new javax.swing.JButton();
        addTerminalButton = new javax.swing.JButton();
        removeTerminalButton = new javax.swing.JButton();
        adjustPowerLabel1 = new javax.swing.JLabel();
        adjustPowerLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoDisplay.setColumns(20);
        infoDisplay.setRows(5);
        jScrollPane1.setViewportView(infoDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 47, 590, 600));

        displayInfoButton.setText("Display System Information");
        displayInfoButton.setToolTipText("");
        displayInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayInfoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayInfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 562, 104));

        displayShortestPathButton.setText("Display Shortest Paths");
        displayShortestPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayShortestPathButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayShortestPathButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 770, 562, 100));

        gridLosses.setColumns(20);
        gridLosses.setRows(5);
        gridLosses.setText("Lost Connections: \nLost Terminals: ");
        jScrollPane3.setViewportView(gridLosses);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 404, 136));

        gridStatus.setColumns(20);
        gridStatus.setRows(5);
        gridStatus.setText("Power Grid Status: ");
        jScrollPane4.setViewportView(gridStatus);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, 406, 101));

        updateInformationButton.setText("Update Information");
        updateInformationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInformationButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateInformationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, 250, 50));

        updateFromFileButton.setText("Update From File");
        updateFromFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFromFileButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateFromFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 80, 250, 50));

        systemUpdatesButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        systemUpdatesButton.setText("System Updates:");
        getContentPane().add(systemUpdatesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 362, 34));

        adjustPowerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        adjustPowerLabel.setText("Adjust Terminals");
        getContentPane().add(adjustPowerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 770, -1, -1));

        buildingNameField.setText("Enter Building Name");
        buildingNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(buildingNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 404, 45));

        amountOfPowerField.setText("Amount of Power");
        getContentPane().add(amountOfPowerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 404, 42));

        adjustPowerButton.setText("Adjust Power");
        adjustPowerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustPowerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(adjustPowerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 400, 260, 86));

        mainPageButton.setText("Back to Main Page");
        mainPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPageButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mainPageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 940, 255, 62));

        displayConnectionsButton.setText("Display Connections");
        displayConnectionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayConnectionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(displayConnectionsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 880, 562, 106));

        firstHubNameField.setText("Enter Name of First Hub");
        getContentPane().add(firstHubNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 400, 60));

        secondHubNameField.setText("Enter Name of Second Hub");
        getContentPane().add(secondHubNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 670, 400, 60));

        terminalNameField.setText("Enter Name of Terminal");
        getContentPane().add(terminalNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 800, 400, 70));

        addConnectionButton.setText("Add Connection");
        addConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConnectionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addConnectionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 590, 300, 60));

        removeConnectionButton.setText("Remove Connection");
        removeConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConnectionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeConnectionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 680, 310, 60));

        addTerminalButton.setText("Add Terminal");
        addTerminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTerminalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addTerminalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 800, 320, 40));

        removeTerminalButton.setText("Remove Terminal");
        removeTerminalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTerminalButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeTerminalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 850, 320, 40));

        adjustPowerLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        adjustPowerLabel1.setText("Adjust Power:");
        getContentPane().add(adjustPowerLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        adjustPowerLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        adjustPowerLabel2.setText("Adjust Connections");
        getContentPane().add(adjustPowerLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayShortestPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayShortestPathButtonActionPerformed
        // TODO add your handling code here:
        infoDisplay.setText(powerGrid.displayShortestPaths());
    }//GEN-LAST:event_displayShortestPathButtonActionPerformed
    
    private void displayInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayInfoButtonActionPerformed
        // TODO add your handling code here:
        infoDisplay.setText(powerGrid.displayInformation());
    }//GEN-LAST:event_displayInfoButtonActionPerformed

    private void updateFromFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFromFileButtonActionPerformed
        // TODO add your handling code here:
        String updates = powerGrid.updateGrid();
        
        String[] splitUpdates = updates.split("/");
        String lostConnections = splitUpdates[0].trim();
        String lostTerminals = splitUpdates[1].trim();
        String result = "";
        result += lostConnections + "\n" + lostTerminals;
        gridLosses.setText(result);
        
        infoDisplay.setText(powerGrid.displayInformation());
        
        checkStatus();
    }//GEN-LAST:event_updateFromFileButtonActionPerformed

    private void checkStatus()
    {
        if (powerGrid.checkOperatingPower() && powerGrid.checkOperatingBuildings() && powerGrid.checkOperatingConnections())
        {
            gridStatus.setText("Power Grid Status: Running Successfully");
        }
        else
        {
            gridStatus.setText("Power Grid Status: Failing to Run");
        }
        
        if (!powerGrid.checkOperatingPower())
        {
            gridStatus.setText(gridStatus.getText() + "\n" + "Excess Power Required: " + (powerGrid.getPowerRequired()-powerGrid.getPower()) + "kw/hr");
        }
        
        if (!powerGrid.checkOperatingBuildings())
        {
            gridStatus.setText(gridStatus.getText() + "\n" + "Failing Buildings: " + powerGrid.getFailingBuildings());
        }
        
        if (!powerGrid.checkOperatingConnections())
        {
            gridStatus.setText(gridStatus.getText() + "\n" + "Disconnected Buildings: " + powerGrid.getDisconnectedBuildings());
        }
    }
    
    private void updateInformationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInformationButtonActionPerformed
        // TODO add your handling code here:
        checkStatus();
    }//GEN-LAST:event_updateInformationButtonActionPerformed

    private void buildingNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingNameFieldActionPerformed

    private void adjustPowerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustPowerButtonActionPerformed
        // TODO add your handling code here:
        powerGrid.adjustPower(buildingNameField.getText(), Integer.parseInt(amountOfPowerField.getText().trim()));
        infoDisplay.setText(powerGrid.displayInformation());
        checkStatus();
        buildingNameField.setText("Enter Building Name");
        amountOfPowerField.setText("Amount of Power");
    }//GEN-LAST:event_adjustPowerButtonActionPerformed

    private void displayConnectionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayConnectionsButtonActionPerformed
        // TODO add your handling code here:
        infoDisplay.setText(powerGrid.displayConnections());
    }//GEN-LAST:event_displayConnectionsButtonActionPerformed

    private void addConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConnectionButtonActionPerformed
        // TODO add your handling code here:
        powerGrid.addConnection(firstHubNameField.getText(), secondHubNameField.getText());
        firstHubNameField.setText("Enter Name of First Hub");
        secondHubNameField.setText("Enter Name of Second Hub");
        infoDisplay.setText(powerGrid.displayInformation());
        checkStatus();
    }//GEN-LAST:event_addConnectionButtonActionPerformed

    private void removeConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConnectionButtonActionPerformed
        // TODO add your handling code here:
        powerGrid.removeConnection(firstHubNameField.getText(), secondHubNameField.getText());
        firstHubNameField.setText("Enter Name of First Hub");
        secondHubNameField.setText("Enter Name of Second Hub");
        checkStatus();
        infoDisplay.setText(powerGrid.displayInformation());
    }//GEN-LAST:event_removeConnectionButtonActionPerformed

    private void addTerminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTerminalButtonActionPerformed
        // TODO add your handling code here:
        powerGrid.addHub(terminalNameField.getText());
        terminalNameField.setText("Enter Name of Terminal");
        checkStatus();
        infoDisplay.setText(powerGrid.displayInformation());
    }//GEN-LAST:event_addTerminalButtonActionPerformed

    private void removeTerminalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTerminalButtonActionPerformed
        // TODO add your handling code here:
        powerGrid.removeHub(terminalNameField.getText());
        terminalNameField.setText("Enter Name of Terminal");
        checkStatus();
        infoDisplay.setText(powerGrid.displayInformation());
    }//GEN-LAST:event_removeTerminalButtonActionPerformed

    private void mainPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPageButtonActionPerformed
        try {
            // TODO add your handling code here:
            powerGrid.rewriteFile();
        } catch (IOException ex) {
            Logger.getLogger(PowerGridFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        MainFrame main = new MainFrame();
        dispose();
        main.setVisible(true);
    }//GEN-LAST:event_mainPageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PowerGridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PowerGridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PowerGridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PowerGridFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConnectionButton;
    private javax.swing.JButton addTerminalButton;
    private javax.swing.JButton adjustPowerButton;
    private javax.swing.JLabel adjustPowerLabel;
    private javax.swing.JLabel adjustPowerLabel1;
    private javax.swing.JLabel adjustPowerLabel2;
    private javax.swing.JTextField amountOfPowerField;
    private javax.swing.JTextField buildingNameField;
    private javax.swing.JButton displayConnectionsButton;
    private javax.swing.JButton displayInfoButton;
    private javax.swing.JButton displayShortestPathButton;
    private javax.swing.JTextField firstHubNameField;
    private javax.swing.JTextArea gridLosses;
    private javax.swing.JTextArea gridStatus;
    private javax.swing.JTextArea infoDisplay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton mainPageButton;
    private javax.swing.JButton removeConnectionButton;
    private javax.swing.JButton removeTerminalButton;
    private javax.swing.JTextField secondHubNameField;
    private javax.swing.JLabel systemUpdatesButton;
    private javax.swing.JTextField terminalNameField;
    private javax.swing.JButton updateFromFileButton;
    private javax.swing.JButton updateInformationButton;
    // End of variables declaration//GEN-END:variables
}
