
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 236605
 */
public class PromotionPanel extends javax.swing.JFrame {

    private Colony colonyData;
    /**
     * Creates new form PromotionPanel
     */
    public PromotionPanel() throws FileNotFoundException {
        initComponents();
        colonyData = new Colony();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newPositionLabel = new javax.swing.JLabel();
        newPositionInput = new javax.swing.JTextField();
        rankIDLabel = new javax.swing.JLabel();
        rankIDInput = new javax.swing.JTextField();
        enter = new javax.swing.JButton();
        successLabel = new javax.swing.JLabel();
        backtoMain = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        newPositionsPossible = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(getPreferredSize());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newPositionLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        newPositionLabel.setText("Enter New Position (Code) Below");
        getContentPane().add(newPositionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 430, 90));

        newPositionInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newPositionInput.setText("Enter New Position");
        getContentPane().add(newPositionInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 790, 80));

        rankIDLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rankIDLabel.setText("Enter Colonist Rank ID Below");
        getContentPane().add(rankIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 430, 90));

        rankIDInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rankIDInput.setText("Enter Rank ID");
        getContentPane().add(rankIDInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 790, 80));

        enter.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 300, 60));

        successLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(successLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 770, 110));

        backtoMain.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backtoMain.setText("Back To Personnel");
        backtoMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoMainActionPerformed(evt);
            }
        });
        getContentPane().add(backtoMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 800, 690, 190));

        newPositionsPossible.setColumns(20);
        newPositionsPossible.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        newPositionsPossible.setRows(5);
        newPositionsPossible.setText("01 Top Commander(Command Center)\n02 2nd Commander(Storage Facility/Junk Yard)\n11 Head Of Research Building\n21 Head Of Hydroponics/Greenhouse\n31 Head Of Engineering(Machinist/Smelter)\n41 Head Of Water Treatment Facility\n51 Head Of Hospital");
        jScrollPane1.setViewportView(newPositionsPossible);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 510, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        try {
            String rankID = rankIDInput.getText();
            String newPosition = newPositionInput.getText();
            colonyData.promote(rankID, newPosition);
            successLabel.setText("Promotion Successful");
        } catch (IOException ex) {
            Logger.getLogger(PromotionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enterActionPerformed

    private void backtoMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoMainActionPerformed
        try {
            PersonnelPanel p = new PersonnelPanel();
            p.setVisible(true);
            dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PromotionPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backtoMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromotionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromotionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromotionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromotionPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PromotionPanel().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(PromotionPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoMain;
    private javax.swing.JButton enter;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newPositionInput;
    private javax.swing.JLabel newPositionLabel;
    private javax.swing.JTextArea newPositionsPossible;
    private javax.swing.JTextField rankIDInput;
    private javax.swing.JLabel rankIDLabel;
    private javax.swing.JLabel successLabel;
    // End of variables declaration//GEN-END:variables
}
